name: Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SFTP Deploy to Bluehost
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT }}
          protocol: sftp
          local-dir: ./
          server-dir: ${{ secrets.SFTP_TARGET }}
          log-level: verbose
